version: '3.8'

services:
  postgres:
    image: postgres:14.4-alpine
    volumes:
      - data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  app:
    build:
      context: ../
      dockerfile: infra/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    entrypoint:
      [ "/app/infra/docker-entrypoint.sh" ]
    env_file:
      - ./.env
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - postgres

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/

volumes:
  data:
  static_value:
  media_value:
