# Generated by Django 4.2.7 on 2024-10-01 10:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Breed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Порода кошки",
                "verbose_name_plural": "Породы кошек",
            },
        ),
        migrations.CreateModel(
            name="Cat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("gray", "Серый"),
                            ("black", "Черный"),
                            ("white", "Белый"),
                            ("ginger", "Рыжий"),
                            ("ginger", "Рыжий"),
                            ("mixed", "Смешанный"),
                        ],
                        max_length=20,
                    ),
                ),
                ("birth_date", models.DateField()),
                ("description", models.TextField(max_length=500)),
            ],
            options={
                "verbose_name": "Кошка",
                "verbose_name_plural": "Кошки",
            },
        ),
        migrations.CreateModel(
            name="CatRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "cat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cats.cat"
                    ),
                ),
            ],
            options={
                "verbose_name": "Рейтинг",
                "verbose_name_plural": "Рейтинги",
            },
        ),
    ]
