# Generated by Django 4.2.7 on 2024-10-04 10:10

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cats", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cat",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cat",
            name="birth_date",
            field=models.DateField(
                validators=[
                    django.core.validators.MaxValueValidator(datetime.date.today)
                ],
                verbose_name="Дата рождения",
            ),
        ),
        migrations.AlterField(
            model_name="cat",
            name="breed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cats.breed",
                verbose_name="Порода",
            ),
        ),
        migrations.AlterField(
            model_name="cat",
            name="color",
            field=models.CharField(
                choices=[
                    ("gray", "Серый"),
                    ("black", "Черный"),
                    ("white", "Белый"),
                    ("ginger", "Рыжий"),
                    ("ginger", "Рыжий"),
                    ("mixed", "Смешанный"),
                ],
                max_length=20,
                verbose_name="Цвет",
            ),
        ),
        migrations.AlterField(
            model_name="cat",
            name="description",
            field=models.TextField(max_length=500, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="catrating",
            name="cat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cats.cat",
                verbose_name="Кошка",
            ),
        ),
        migrations.AlterField(
            model_name="catrating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="catrating",
            name="value",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Рейтинг",
            ),
        ),
    ]
