# Generated by Django 4.2.7 on 2024-10-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cats", "0003_cat_author_alter_cat_birth_date_alter_cat_breed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breed",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
